/*MODOFICAR FILAS / ACTUALIZAR DATOS*/
#TENER MUCHO CUAIDADO NUNCA USAR EL UPDATE SIN UN WHERE, YA QUE PODRIAMOS ACTUALIZAR TODA LA TABLA SI NO ESPESIFICMOS EL CAMPO#
UPDATE usuarios SET apellidos = 'Velasco', fecha = '2019-07-09'  WHERE  id = 4;